title: Kartikeya Saraswat
logo: /assets/kartik.jpg
#description: text below image
show_downloads: true
theme: bulma-clean-theme
# remote_theme: pages-themes/modernist@v0.2.0
# plugins:
# - jekyll-remote-theme 
